`include "../system-rtl/gop16.v"
`include "../system-rtl/ram4k.v"
`include "../system-rtl/uart.v"
`include "../system-rtl/i2cslave.v"
`include "../system-rtl/tinybootrom.v"
`include "../cpu.v"
`include "../ALU.v"
